translation macro (SDCP-392) always overwrite existing destinations with the french version. [SDESK-5813]
superdesk/superdesk-cp pull request #112
Opened 2021-02-15 08:52 UTC by GyanP

2021-02-15 14:53 UTC, petrjasek commented
not sure exactly what it does, can you add a test pls?

2021-02-16 10:17 UTC, jerome-poisson requested changes

2021-02-16 10:17 UTC, jerome-poisson commented on server/cp/macros/update_translation_metadata_macro.py
> +fields = ["Presse Canadienne staff", "L'Associated Press", "Canadian Press Staff", "The Associated Press"]
it would be better to use `qcode` instead of names, so if names are updated the macro won't have to be modified.

2021-02-16 10:17 UTC, jerome-poisson commented on server/cp/macros/update_translation_metadata_macro.py
> +    subjects = [sub for sub in subjects if sub.get("name") in fields and sub.get("scheme") == "destinations"]
To follow on above comment, it would be better to use `qcode` instead of `name` here.

2021-02-16 10:17 UTC, jerome-poisson commented on server/cp/macros/update_translation_metadata_macro.py
> +            }) if destination else None
The `else None` is useless here, it should be:
```python
if destination:
    subject.update(
        {
            "name": destination.get("name"),
            "qcode": destination.get("qcode"),
            "scheme": "destinations",
        }
    )
```

2021-02-16 11:28 UTC, jerome-poisson approved these changes

2021-02-16 13:45 UTC, merged